INSERT INTO books (book_name, author, finished)
VALUES  ("The Great Influenza", "John M. Barry", false)
INSERT INTO books (book_name, author, finished)
VALUES  ("Sillness is the Key", "Ryan Holiday", true)
INSERT INTO books (book_name, author, finished)
VALUES  ("Rise to Globalism", "Stephen E. Ambrose", true)
INSERT INTO books (book_name, author, finished)
VALUES  ("It Was ALL A Lie", "Stuart Stevens", true)
INSERT INTO books (book_name, author, finished)
VALUES  ("The Lean Startup", "Eric Ries", false)
INSERT INTO books (book_name, author, finished)
VALUES  ("The Great Influenza", "John M. Barry", false)
INSERT INTO books (book_name, author, finished)
VALUES  ("Grant", "Ron Chernow", true)
INSERT INTO books (book_name, author, finished)
VALUES  ("The Guns of August", "Barbara W. Tuchman", true)
INSERT INTO books (book_name, author, finished)
VALUES  ("The Storm Before the Storm", "John M. Barry", true)
INSERT INTO books (book_name, author, finished)
VALUES  ("1776", "David McCullough", true)
INSERT INTO books (book_name, author, finished)
VALUES  ("The War of Art", "Steven Pressfield", false)
